import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#fef7ff",
        "surface-dim": "#dfd7e6",
        "surface-bright": "#fef7ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f9f1ff",
        "surface-container": "#f3ebfa",
        "surface-container-high": "#ede5f4",
        "surface-container-highest": "#e8dfee",
        "on-surface": "#1d1a24",
        "on-surface-variant": "#4a4455",
        outline: "#7b7487",
        "outline-variant": "#ccc3d8",
        "surface-tint": "#732ee4",
        primary: "#7C3AED",
        "on-primary": "#ffffff",
        "primary-container": "#7c3aed",
        "on-primary-container": "#ede0ff",
        "inverse-primary": "#d2bbff",
        secondary: "#1b6b4f",
        "on-secondary": "#ffffff",
        "secondary-container": "#a6f2cf",
        "on-secondary-container": "#247155",
        tertiary: "#6e5e0d",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#bfab56",
        "on-tertiary-container": "#4b3f00",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#eaddff",
        "primary-fixed-dim": "#d2bbff",
        "on-primary-fixed": "#25005a",
        "on-primary-fixed-variant": "#5a00c6",
        "secondary-fixed": "#a6f2cf",
        "secondary-fixed-dim": "#8bd6b4",
        "on-secondary-fixed": "#002115",
        "on-secondary-fixed-variant": "#00513a",
        "tertiary-fixed": "#f9e287",
        "tertiary-fixed-dim": "#dcc66e",
        "on-tertiary-fixed": "#221b00",
        "on-tertiary-fixed-variant": "#534600",
        background: "#fef7ff",
        "on-background": "#1d1a24",
        "surface-variant": "#e8dfee",
        pastel: {
          purple: "#E9D5FF",
          green: "#A7F3D0",
          yellow: "#FDE68A",
        },
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "12px",
        md: "24px",
        lg: "48px",
        xl: "80px",
        gutter: "24px",
        "container-max": "1200px",
      },
      fontFamily: {
        display: ["Playfair Display", "serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["36px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-sm": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "700" }],
      },
      maxWidth: {
        "container-max": "1200px",
      },
    },
  },
  plugins: [],
};
export default config;
